name: main workflow


on:
 push:
  branches: ["main"]

jobs:
  caller-reusable:
   uses: ./.github/workflows/original-workflow.yaml


  call-reusable_from_another_repo:
    uses: anukaran007/reusablerepo/.github/workflows/another_repo_workflow.yaml@main
  
